//
// Created by nicomane on 09/06/22.
//

#ifndef COMPUTERGRAPHICS_VULKAN_ROCKET_SIMULATOR_TERRAINGENERATOR_H
#define COMPUTERGRAPHICS_VULKAN_ROCKET_SIMULATOR_TERRAINGENERATOR_H


namespace Engine{
    class TerrainGenerator {

    };
}



#endif //COMPUTERGRAPHICS_VULKAN_ROCKET_SIMULATOR_TERRAINGENERATOR_H
