//
// Created by nicomane on 01/07/22.
//

#ifndef COMPUTERGRAPHICS_VULKAN_ROCKET_SIMULATOR_LIGHT_H
#define COMPUTERGRAPHICS_VULKAN_ROCKET_SIMULATOR_LIGHT_H


class Light {

};


#endif //COMPUTERGRAPHICS_VULKAN_ROCKET_SIMULATOR_LIGHT_H
